# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Dat's home
description:      'A programmer, data scientist'
baseurl:          /

paginate:         5

# Custom vars
linkedin:         https://linkedin.com/in/lenguyenthedat

github:           https://github.com/lenguyenthedat
